spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,log4j,wall
    url: jdbc:mysql://localhost:3306/myblog?characterEncoding=UTF-8&useUnicode=true
  redis:
    host: localhost

  mail:
    username: qq邮箱地址
    password: QQ邮箱去获取的一个码值
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 开启驼峰命名方式
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.yu.mybatisplus.pojo
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 8080
  ssl:
    key-store: 配置https的ssl文件地址
    key-store-password: 下载文件的密码